RESULT = a.out
SOURCES = a.ml
PACKS = graphics,extlib
INCDIRS = ~/src/ocaml-mylib
LIBS = mylib
THREADS = yes
ANNOTATE = yes
OCAMLFLAGS = -bin-annot -w A-44

all: native-code

export OCAMLMAKEFILE = ~/src/ocamlmakefile/OCamlMakefile
include $(OCAMLMAKEFILE)
